### ISSUE TITLE
Submit to CKEditor Addon-Repository

### ISSUE THREAD

**Issue by NielsNet** [mlewand/ckeditor-plugin-openlink#11]
Hi,

It might be a good idea to submit this plugin to the Addon-Repository.

**Comment by mlewand** [comment]
@NielsNet it makes a perfect sense. We'll have a busy week now, so I can't promise I'll do that now, but I'll try to get it there some time this month.

Until it's done I'll keep the issue open.

**Comment by mlewand** [comment]
It took a little longer that I initially said but, oh boy, it finally happened!

The plugin is available in addons repo: https://ckeditor.com/cke4/addon/openlink

🎉🎉🎉
