### ISSUE TITLE
unzip folder mismatch with config

### ISSUE THREAD

**Issue by jeffrichards** [mlewand/ckeditor-plugin-openlink#14]
Just a heads up on manual installations the zip file (zip file from https://ckeditor.com/cke4/addon/openlink) when you extract it adds the plugin code in the folder "ckeditor-plugin-openlink" after adjusting my extraPlugins to add the openlink.  I had to rename the "ckeditor-plugin-openlink" folder to "openlink" to get everything working.  

Thanks for the plugin, it's just what I needed.

**Comment by mlewand** [comment]
Actually that might complicate things for some, didn't think about it while uploading. I'll leave it open, so that I remember about it next time I deploy it to the Addons Repo.

Thanks for the heads up 👍
