### ISSUE TITLE
CKEditor Openlink on iPad

### ISSUE THREAD

**Issue by shram2k** [mlewand/ckeditor-plugin-openlink#17]
This plugin works fine for windows however how to achieve link open functionality on iPad.

**Comment by mlewand** [comment]
Using inline balloon that we created a while ago seems to be a perfect fit for this.

See this docs example: https://ckeditor.com/docs/ckeditor4/latest/examples/balloontoolbar.html

It uses the [`linkballoon` plugin](https://github.com/mlewand/ckeditor4-plugin-linkballoon) (which integrates inline toolbar with openlink plugin).

Unfortunately I didn't publish it to the addons repository, so no super-easy installation with CKE4 online builder, and I might not have the time to do that in foreseeable future. So you can just grab the plugin's source files and add it manually to your CKEditor :slightly\_smiling\_face:

**Comment by shram2k** [comment]
Does balloon toolbar work in readonly mode?

**Comment by mlewand** [comment]
In this particular sample it does not, but I believe it should be possible to set it up so that it works in readonly mode. You need to look for that.
