### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by phineas-gage** [mlewand/ckeditor-plugin-openlink#20]
Hi, 

I would like to report a security vulnerability, Is it possible to provide a preferred security contact or to [enable private vulnerability reporting ](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository)on the repo so that this can be reported in confidence?  

Thanks in advance, 

Phil

**Comment by mlewand** [comment]
Thanks, option for reporting vulnerabilities enabled :+1:
