### ISSUE TITLE
Cannot open link in preview mode

### ISSUE THREAD

**Issue by radpet** [mlewand/ckeditor-plugin-openlink#7]
Hello, 

This ticket says that this plugin allows to open links by single clicking them when the editor is in preview mode (readOnly). However, I am not experiencing this feature :). Any ideas why? I have set `config.openlink_enableReadOnly`  to true but nothing changes. Thanks in advance !

**Comment by mlewand** [comment]
Hi @radpet - opening links in readOnly mode works for me (just checked on Chrome and Firefox). You need to make sure you have this config variable enabled, and it's pretty much all it takes to get it working.

```
config.openlink_enableReadOnly = true
```

Please double check if you're [setting configuration correctly](http://docs.ckeditor.com/#!/guide/dev_configuration) and if you can still reproduce the issue.

**Comment by radpet** [comment]
Hi, yea I had it. Nevermind we don't use it anymore you can close the issue if you cannot reproduce it :)

**Comment by mlewand** [comment]
Thanks!
